In [31]:
import pandas as pd
import datetime

### Load the Data

In [32]:
source = 'C:\\Users\\wavac\\Bangkit\\Machine Learning Assignment\\Dataset\\posts.csv'

posts = pd.read_csv(source, index_col=0,  names=['post_id','title','blogger_name','blogger_id','num_of_comment','content','url','date','retrieved_links','retrieved_comment','num_words_s','num_words','avg_word_len_s',
                           'avg_word_len','MEIBI','MEIBIX'])

In [33]:
posts.head()

,title,blogger_name,blogger_id,num_of_comment,content,url,date,retrieved_links,retrieved_comment,num_words_s,num_words,avg_word_len_s,avg_word_len,MEIBI,MEIBIX
post_id,,,,,,,,,,,,,,,
1,We Just Tested Twitter&#8217;s @anywhere Platf...,Jason Kincaid,1,14,"During his keynote at SXSW last month, Twitter...",http://techcrunch.com/2010/04/01/we-just-teste...,2010-04-01,0,14,314,223,4.130293,5.686099,0.0,0.0
2,Facebook To Launch &#8216;Relationships&#8217;...,Jason Kincaid,1,30,Later this month Facebook is holding its f8 co...,http://techcrunch.com/2010/04/01/facebook-to-l...,2010-04-01,0,30,717,488,4.138177,5.952869,0.0,0.0
3,NYTimes Request Correction/Removal Of Our Post...,Michael Arrington,2,38,A NYTimes communications person emailed to ask...,http://techcrunch.com/2010/04/01/nytimes-reque...,2010-04-01,4,38,249,168,3.572614,5.125000,624.0,0.0
4,Google Shows How HTML5 Can Run Quake In The Br...,Erick Schonfeld,3,26,A lot of attention lately has been put on the ...,http://techcrunch.com/2010/04/01/google-html5-...,2010-04-01,10,26,256,172,3.628571,5.168605,1080.0,0.0
5,The iPad: Apple&#8217;s Trojan Horse,John Biggs,4,49,Something struck me about Apple&#8217;s handli...,http://www.crunchgear.com/2010/04/01/the-ipad-...,2010-04-01,1,49,503,348,3.773279,5.356322,200.0,0.0

### Check for empty/null data

In [34]:
null_columns=posts.columns[posts.isnull().any()]
posts[null_columns].isnull().sum()

title       5
content    81
dtype: int64

Since we're not going to use 'Title' and 'Content' for our analysis, we could drop the attributes.

### Strip datetime into individual year, month and day
<br> Since our model cannot handle data in the form of datetime

In [35]:
date = posts['date'].str.split('-',expand=True)
date.columns = ['year','month','day']
posts = posts.join(date)

### Drop unecessary attributes

In [36]:
dropped_columns = ['title','content','url','date']
posts.drop(dropped_columns, axis=1, inplace=True)

### Preprocessed data

In [38]:
posts.head(10)

,blogger_name,blogger_id,num_of_comment,retrieved_links,retrieved_comment,num_words_s,num_words,avg_word_len_s,avg_word_len,MEIBI,MEIBIX,year,month,day
post_id,,,,,,,,,,,,,,
1,Jason Kincaid,1,14,0,14,314,223,4.130293,5.686099,0.0,0.0,2010,04,01
2,Jason Kincaid,1,30,0,30,717,488,4.138177,5.952869,0.0,0.0,2010,04,01
3,Michael Arrington,2,38,4,38,249,168,3.572614,5.125000,624.0,0.0,2010,04,01
4,Erick Schonfeld,3,26,10,26,256,172,3.628571,5.168605,1080.0,0.0,2010,04,01
5,John Biggs,4,49,1,49,503,348,3.773279,5.356322,200.0,0.0,2010,04,01
6,Jason Kincaid,1,13,1,13,299,221,4.393728,5.705882,56.0,0.0,2010,04,01
7,Erick Schonfeld,3,5,1,5,306,220,4.232877,5.618182,24.0,0.0,2010,04,01
8,MG Siegler,5,3,0,3,446,300,4.004673,5.713333,0.0,0.0,2010,04,01
9,Jason Kincaid,1,8,2,8,419,303,4.077670,5.544554,72.0,0.0,2010,04,01
10,MG Siegler,5,36,0,35,304,216,3.955017,5.291667,0.0,0.0,2010,04,01